traefik:
  image: traefik
  command: --web --docker --acme --acme.entryPoint=https --acme.domains=chat.jonathan.pl --acme.email=admin@jonathan.pl --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --acme.storage=acme.json --acme.onDemand=true --docker.domain=docker.localhost --logLevel=INFO
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
    - /opt/acme/acme.json:/acme.json
  labels:
    - "traefik.enable=false"
mongo:
    image: mongo
    volumes:
        - /opt/data:/data/db
    labels:
        - "traefik.enable=false"
anon-chat:
    image: gaetanroche/anon-chat
    links:
        - mongo
    labels:
        - "traefik.port=8080"
        - "traefik.backend=back"
        - "traefik.frontend.rule=Host:chat.jonathan.pl, localhost"
        - "traefik.frontend.entryPoints=http,https"
